# Site settings
title: Gaussian Process and Uncertainty Quantification Summer School, 2020
email:
description: > # this means to ignore newlines until "baseurl:"
  Gaussian Process Summer School
baseurl: "/gpss20" # the subpath of your site, e.g. /blog/
url: "http://gpss.cc" # the base hostname & protocol for your site
logo: "gpss_logo.svg"
twitter_username: sheffieldmlnet
github_username:  gpschool


youtube:
  height: 315
  width: 560

github:
  edit: true
  repository: gpss19

markdown: kramdown

# Build settings
future: true

permalink: "/:categories/:title.html"
banner:

analytics:
 google:
   tracking_id: UA-62991754-1# Google tracking ID if applicable

youtube:
  height: 315
  width: 560

conference:
  draft: false # set to True if the programme is draft only.
  hide_tentative: true
  hosts:

  name: Gaussian Process Summer School
  year: 2020
  month: September
  dates:
  - 2020-09-14
  - 2020-09-15
  - 2020-09-16
  - 2020-09-17
  organizers:
    - {given: Mauricio, family: Alvarez, url: "https://maalvarezl.github.io/", institute: University of Sheffield}
    - {given: Javier, family: Gonzalez, url: "http://javiergonzalezh.github.io/", institute: Microsoft Research Cambridge}
    - {given: Neil D., family: Lawrence, url: "http://inverseprobability.com", institute: University of Cambridge}
    - {given: Richard, family: Wilkinson, url: "http://r-wilkinson.staff.shef.ac.uk/", institute: University of Nottingham}
    - {given: Wil, family: Ward, url: "https://wilocw.github.io/", institute: University of Sheffield}
    - {given: Michael T., family: Smith, url: "http://www.michaeltsmith.org.uk/", institute: University of Sheffield}
    - {given: "", family: Sheffield Machine Learning Group, url: "https://www.sheffield.ac.uk/dcs/research/groups/machine-learning"}

previous_meeting:
  name: Past Meetings
  url: "http://gpss.cc/past_meetings.html"

map:
  show: false
  mapbox:
    latitude: 53.385396 # latitude of map center
    longitude: -1.472726 # longitude of map center
    map_id1: maalvarezl # mapbox id1
    map_id2: cj6hz56fb4q9l2rpajqiqw5ki # mapbox id2
    fresh: true
    title: false
    access_token: pk.eyJ1IjoibWFhbHZhcmV6bCIsImEiOiJjajY1Nmo1b3gxb2d2Mndub2dyeDNsa2IzIn0.qLCz36sKjWARW8EBSy2fAQ # mapbox access token
    zoom_level: 14.5
    width: 100%
    height: 500px
