# Site settings
title: Conference Name, Year
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write a description for your conference or meeting here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/confweb" # the subpath of your site, e.g. /blog/
url: "http://opendsi.cc" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  sods


youtube:
  height: 315
  width: 560

github:
  edit: true
  repository: confweb
  
markdown: kramdown

# Build settings
future: true

permalink: "/:categories/:title.html"
banner: nice_conference_banner.jpeg

analytics:
 google:
   tracking_id: # Google tracking ID if applicable

youtube:
  height: 315
  width: 560

conference:
  draft: true # set to True if the programme is draft only.
  hide_tentative: true
  hosts:
  
  room: Room
  venue: Convention Centre
  location: City, Country
  name: Conference Name
  year: 2017
  month: September
  dates:
  - 2017-09-12
  - 2017-09-13
  hosts:
  general:
  - family: Jones
    given: Jack
    url: "http://jackjones.org"
  - family: Bloggs
    name: Bill
    url: "http://billblogs.org"
  workshop:
  - family:
    given:
    url:
    institute:
  symposium:
  - family:
    given:
    url:
    institute:
  local:
  - family:
    given:
    url:
    institute:
  sponsors:
  - name:
    url:
previous_meeting:
  name:
  url:

map:
  show: False
  mapbox:
    latitude: # latitude of map center
    longitude: # longitude of map center
    map_id: # mapbox id
    access_token: # mapbox access token
    zoom_level: 17
    width: 100%
    height: 500px
